### ISSUE TITLE
Library DataZoomPNADCovid não instalada

### ISSUE THREAD

**Issue by FranciscoCavalcanti** [datazoompuc/PNAD_Covid#1]
Tentei instalar DataZoomPNADCovid no R sem sucesso.

Após instalar o pacote usando a função:

`if(!require(devtools)) install.packages("devtools")
devtools::install_github('datazoompuc/PNAD_Covid/port/R/DataZoomPNADCovid')`

Funcinou normalmente. (Apenas tive que apertar o número "1" para atualizar todos os pacotes)

Em seguida tentei rodar o seguinte código

`library(DataZoomPNADCovid)
`

No entanto deu o seguinte erro:

`Error in library(DataZoomPNADCovid) : 
  there is no package called ‘DataZoomPNADCovid’`

**Comment by arthurcbps** [comment]
Francisco, tem certeza que rodou essas 3 linhas? Eu desinstalei aqui, rodei de novo, e o pacote instalou

**Comment by arthurcbps** [comment]
Tende rodar desta forma:
```
if(!require(devtools)) install.packages("devtools")
devtools::install_github('datazoompuc/PNAD_Covid/port/R/DataZoomPNADCovid')
library(DataZoomPNADCovid)
```

Ou seja, com o código disposto nessas três linhas

**Comment by FranciscoCavalcanti** [comment]
Fiz o que pediu:

Copiei e colei os códigos como disse, e deu o mesmo problema.

Segue o resultado do Console completo:

>  R version 4.0.0 (2020-04-24) -- "Arbor Day"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

>R é um software livre e vem sem GARANTIA ALGUMA.
Você pode redistribuí-lo sob certas circunstâncias.
Digite 'license()' ou 'licence()' para detalhes de distribuição.

>R é um projeto colaborativo com muitos contribuidores.
Digite 'contributors()' para obter mais informações e
'citation()' para saber como citar o R ou pacotes do R em publicações.

>Digite 'demo()' para demonstrações, 'help()' para o sistema on-line de ajuda,
ou 'help.start()' para abrir o sistema de ajuda em HTML no seu navegador.
Digite 'q()' para sair do R.

> if(!require(devtools)) install.packages("devtools")
Carregando pacotes exigidos: devtools
Carregando pacotes exigidos: usethis
Error: package or namespace load failed for ‘usethis’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘glue’
Failed with error:  ‘package ‘usethis’ could not be loaded’
WARNING: Rtools is required to build R packages but is not currently installed. Please download and install the appropriate version of Rtools before proceeding:

>https://cran.rstudio.com/bin/windows/Rtools/
Installing package into ‘C:/Users/Francisco/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
also installing the dependency ‘glue’

>tentando a URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/glue_1.4.1.zip'
Content type 'application/zip' length 154257 bytes (150 KB)
downloaded 150 KB

>tentando a URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/devtools_2.3.0.zip'
Content type 'application/zip' length 351333 bytes (343 KB)
downloaded 343 KB

>package ‘glue’ successfully unpacked and MD5 sums checked
package ‘devtools’ successfully unpacked and MD5 sums checked

>The downloaded binary packages are in
	C:\Users\Francisco\AppData\Local\Temp\RtmpERSBdZ\downloaded_packages
> 
> devtools::install_github('datazoompuc/PNAD_Covid/port/R/DataZoomPNADCovid')
WARNING: Rtools is required to build R packages, but is not currently installed.

>Please download and install Rtools custom from https://cran.r-project.org/bin/windows/Rtools/.
Downloading GitHub repo datazoompuc/PNAD_Covid@master
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

>1: All                             
2: CRAN packages only              
3: None                            
4: ellipsis (0.3.0 -> 0.3.1) [CRAN]
5: pillar   (1.4.3 -> 1.4.4) [CRAN]
6: vctrs    (0.3.0 -> 0.3.1) [CRAN]
7: tibble   (3.0.0 -> 3.0.1) [CRAN]
8: haven    (2.3.0 -> 2.3.1) [CRAN]

>Enter one or more numbers, or an empty line to skip updates:

>WARNING: Rtools is required to build R packages, but is not currently installed.

>Please download and install Rtools custom from https://cran.r-project.org/bin/windows/Rtools/.
√  checking for file 'C:\Users\Francisco\AppData\Local\Temp\RtmpERSBdZ\remotes3bb060c263a0\datazoompuc-PNAD_Covid-b776292\port\R\DataZoomPNADCovid/DESCRIPTION' (1s)
>-  preparing 'DataZoomPNADCovid':
>√  checking DESCRIPTION meta-information
>-  checking for LF line-endings in source and make files and shell scripts
>-  checking for empty or unneeded directories
>-  building 'DataZoomPNADCovid_1.0.tar.gz'
   
>Installing package into ‘C:/Users/Francisco/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
>* installing *source* package 'DataZoomPNADCovid' ...
>** using staged installation
>** R
>** byte-compile and prepare package for lazy loading
>Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace 'haven' 2.3.0 is being loaded, but >= 2.3.1 is required
>Calls: <Anonymous> ... namespaceImportFrom -> asNamespace -> loadNamespace
>Execução interrompida
>ERROR: lazy loading failed for package 'DataZoomPNADCovid'
>* removing 'C:/Users/Francisco/Documents/R/win-library/4.0/DataZoomPNADCovid'
>Erro: Failed to install 'DataZoomPNADCovid' from GitHub:
  (convertido do aviso) installation of package >‘C:/Users/FRANCI~1/AppData/Local/Temp/RtmpERSBdZ/file3bb04f4b51da/DataZoomPNADCovid_1.0.tar.gz’ had non-zero exit status
>Além disso: Warning messages:
>1: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
>2: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
> library(DataZoomPNADCovid)
>Error in library(DataZoomPNADCovid) : 
  there is no package called ‘DataZoomPNADCovid’

**Comment by FranciscoCavalcanti** [comment]
@arthurcbps 

Apenas atualizando.  Eu ainda não consegui instalar o pacote.

Passo a passo do que eu estou fazendo:

**1) Abrir o R-Studio
2) Abrir um R-Script novo
3) Inserir o seguindo código**
`if(!require(devtools)) install.packages("devtools")
devtools::install_github('datazoompuc/PNAD_Covid/port/R/DataZoomPNADCovid')`

**Output:**

`
```
Carregando pacotes exigidos: devtools
Carregando pacotes exigidos: usethis
Warning message:
package ‘devtools’ was built under R version 4.0.2 
> devtools::install_github('datazoompuc/PNAD_Covid/port/R/DataZoomPNADCovid')
WARNING: Rtools is required to build R packages, but is not currently installed.

Please download and install Rtools custom from https://cran.r-project.org/bin/windows/Rtools/.
Erro: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  Not Found

  Did you spell the repo owner (`datazoompuc`) and repo name (`PNAD_Covid`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.
> library(DataZoomPNADCovid)
Error in library(DataZoomPNADCovid) : 
  there is no package called ‘DataZoomPNADCovid’
> if(!require(devtools)) install.packages("devtools")
> devtools::install_github('datazoompuc/PNAD_Covid/port/R/DataZoomPNADCovid')
WARNING: Rtools is required to build R packages, but is not currently installed.

Please download and install Rtools custom from https://cran.r-project.org/bin/windows/Rtools/.
Erro: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  Not Found

  Did you spell the repo owner (`datazoompuc`) and repo name (`PNAD_Covid`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.
> library(DataZoomPNADCovid)
Error in library(DataZoomPNADCovid) : 
  there is no package called ‘DataZoomPNADCovid’
> if(!require(devtools)) install.packages("devtools")
> devtools::install_github('datazoompuc/PNAD_Covid/port/R/DataZoomPNADCovid')
WARNING: Rtools is required to build R packages, but is not currently installed.

Please download and install Rtools custom from https://cran.r-project.org/bin/windows/Rtools/.
Erro: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  Not Found

  Did you spell the repo owner (`datazoompuc`) and repo name (`PNAD_Covid`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.
```

**4) Inserir o seguindo código:**

`
library(DataZoomPNADCovid)
`

**Output**:

`
Error in library(DataZoomPNADCovid) : 
  there is no package called ‘DataZoomPNADCovid’
`

**Comment by arthurcbps** [comment]
Francisco, tente instalar o Rtools - para mim era uma ferramenta usada só para criação de pacotes, e não instalação. Eu atualizei um tempo atrás por algum motivo e deu certo. https://cran.r-project.org/bin/windows/Rtools/

Se der certo depois de instalado, deve ser por isso mesmo. Ainda assim, vou ver se tem como contornar isso

**Comment by FranciscoCavalcanti** [comment]
Oi @arthurcbps.

Mesmo após instalar o Rtoots como sugerido, o problema persiste. Segue abaixo o resultado no Console:

Código:
```
if(!require(devtools)) install.packages("devtools")
```
Funcionou.
Código em seguida:

```
devtools::install_github('datazoompuc/PNAD_Covid/port/R/DataZoomPNADCovid')
Erro: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  Not Found

  Did you spell the repo owner (`datazoompuc`) and repo name (`PNAD_Covid`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.
```

Não funcionou.
Código em seguida:

```
library(DataZoomPNADCovid)
Error in library(DataZoomPNADCovid) : 
  there is no package called ‘DataZoomPNADCovid’
```

**Comment by arthurcbps** [comment]
Francisco, acredito que agora o erro seja pois mudamos a organização das pastas no github, de forma que o endereço estaria errado.  Tente mudar o endereço de acordo com a estrutura das pastas. Por isso, seria bom que, dentro da pasta PNAD_Covid/R, criássemos uma outra com o nome do pacote, onde estariam os arquivos usados nessa instalação. Ao final, ficaria alto deste tipo:
`devtools::install_github('datazoompuc/PNAD_Covid/R/DataZoomPNADCovid')`

**Comment by FranciscoCavalcanti** [comment]
Segui a instruções no Readme.md 
```

if(!require(devtools)) install.packages("devtools")

devtools::install_github('datazoompuc/PNAD_Covid/R/datazoom_pnad_covid')

```
O resultado:

```


Downloading GitHub repo datazoompuc/PNAD_Covid@master
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

 1: All                               
 2: CRAN packages only                
 3: None                              
 4: dplyr    (1.0.0   -> 1.0.1) [CRAN]
 5: rlang    (0.4.6   -> 0.4.7) [CRAN]
 6: ellipsis (0.3.0   -> 0.3.1) [CRAN]
 7: pillar   (1.4.3   -> 1.4.6) [CRAN]
 8: vctrs    (0.3.0   -> 0.3.2) [CRAN]
 9: Rcpp     (1.0.4.6 -> 1.0.5) [CRAN]
10: tibble   (3.0.0   -> 3.0.3) [CRAN]
11: haven    (2.3.0   -> 2.3.1) [CRAN]

Enter one or more numbers, or an empty line to skip updates:

√  checking for file 'C:\Users\Francisco\AppData\Local\Temp\RtmpqgTvzN\remotes4a4051fb1ab8\datazoompuc-PNAD_Covid-c5e4778\R\datazoom_pnad_covid/DESCRIPTION' (604ms)
-  preparing 'datazoomPNADcovid':
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'datazoomPNADcovid_1.0.tar.gz'
   
Installing package into ‘C:/Users/Francisco/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
* installing *source* package 'datazoomPNADcovid' ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace 'haven' 2.3.0 is being loaded, but >= 2.3.1 is required
Calls: <Anonymous> ... namespaceImportFrom -> asNamespace -> loadNamespace
Execução interrompida
ERROR: lazy loading failed for package 'datazoomPNADcovid'
* removing 'C:/Users/Francisco/Documents/R/win-library/4.0/datazoomPNADcovid'
Erro: Failed to install 'datazoomPNADcovid' from GitHub:
  (convertido do aviso) installation of package ‘C:/Users/FRANCI~1/AppData/Local/Temp/RtmpqgTvzN/file4a405c8e576f/datazoomPNADcovid_1.0.tar.gz’ had non-zero exit status`

```
``
